name = "FractionalSystems"
uuid = "43fecb94-217b-4542-9f6a-a624b53b7d19"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.1.3"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
ControlSystems = "0.11"
Roots = "1.3.14"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
