name = "FractionalSystems"
uuid = "43fecb94-217b-4542-9f6a-a624b53b7d19"
authors = ["Qingyu Qu <erikqqy123@gmail.com>"]
version = "0.1.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"

[compat]
ControlSystems = "0.11"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
